### PR TITLE
jwtoken expiration

### PR DESCRIPTION
**Pull request by martinklepsch**
based on #4 & #5 — [trello card](https://trello.com/c/BQw0hCd0/433-jwtoken-expiration-off-boarding-use-case)

Web PR: https://github.com/open-company/open-company-web/pull/122
API PR: https://github.com/open-company/open-company-api/pull/47

### CODE REVIEW

**Comment by belucid** [comment]
@martinklepsch make sure you assign these when they are ready for review

**Comment by martinklepsch** [comment]
I will when they are for now they are based on another PR so review isn't
yet useful.

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@martinklepsch this fails badly for existing tokens:

http://take.ms/9fxAx

java.lang.AssertionError: Assert failed: clj-slack: Access token is not valid. :token has to be a non-empty string, but is nil

**Comment by belucid** [comment]
@martinklepsch this seems to work well for new tokens, but we need to do better than 500 when there is a request to refresh an existing old token.

**Comment by martinklepsch** [comment]
@belucid ready again, make sure you also re-fetch the web PR

**Pull request merged**
