### PR TITLE
Jwt slack auth

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/Ee4lE6Dd

review with this:
https://github.com/open-company/open-company-web/pull/24

to test:
- deploy this branch on staging (use auth-service branch of infrastructure)
- deploy [user-auth](https://github.com/open-company/open-company-web/pull/24) branch of open-company-web too
- open this page [https://staging.opencompany.io/login](https://staging.opencompany.io/login) on your browser
- tap on the slack button
- after you login with slack you should be redirected to https://staging.opencompany.io/companies
- check the cookies, you should have one called `jwt` containing you token
- check the last requests to the API server, all these should contains a `Authorization` cookie containing a value like `Bearer {you JWT token}`

tests are TBD

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 I get an NPE on `/test-token`

**Comment by belucid** [comment]
@bago2k4 before updating dependencies, `lein test!` gets an NPE due to not picking up the dev/QA passphrase from `project.clj` with environ.

**Comment by belucid** [comment]
@bago2k4 after dependency updates, `lein test!` fails with:

```
Exception in thread "main" java.lang.IllegalArgumentException: No matching method: sha1Hex, compiling:(such/random.clj:17:3)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6882)
    at clojure.lang.Compiler.analyze(Compiler.java:6676)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6863)
    at clojure.lang.Compiler.analyze(Compiler.java:6676)
    at clojure.lang.Compiler.analyze(Compiler.java:6632)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6008)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5389)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3957)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6873)
    at clojure.lang.Compiler.analyze(Compiler.java:6676)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6863)
    at clojure.lang.Compiler.analyze(Compiler.java:6676)
    at clojure.lang.Compiler.access$300(Compiler.java:38)
    at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:588)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
    at clojure.lang.Compiler.analyze(Compiler.java:6676)
    at clojure.lang.Compiler.analyze(Compiler.java:6632)
    at clojure.lang.Compiler.eval(Compiler.java:6938)
    at clojure.lang.Compiler.load(Compiler.java:7381)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.loadResourceScript(RT.java:363)
    at clojure.lang.RT.load(RT.java:453)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5661.invoke(core.clj:5883)
    at clojure.core$load.invokeStatic(core.clj:5882)
    at clojure.core$load_one.invokeStatic(core.clj:5683)
    at clojure.core$load_one.invoke(core.clj)
    at clojure.core$load_lib$fn__5610.invoke(core.clj:5728)
    at clojure.core$load_lib.invokeStatic(core.clj:5727)
    at clojure.core$load_lib.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:647)
    at clojure.core$load_libs.invokeStatic(core.clj:5765)
    at clojure.core$load_libs.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:647)
    at clojure.core$require.invokeStatic(core.clj:5787)
    at clojure.core$require.doInvoke(core.clj)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at such.immigration$import_all_vars$expand__435.invoke(immigration.clj:45)
    at such.immigration$import_all_vars$fn__437.invoke(immigration.clj:47)
    at clojure.core$map$fn__4770.invoke(core.clj:2639)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.next(RT.java:688)
    at clojure.lang.Compiler.eval(Compiler.java:6922)
    at clojure.lang.Compiler.load(Compiler.java:7381)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.loadResourceScript(RT.java:363)
    at clojure.lang.RT.load(RT.java:453)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5661.invoke(core.clj:5883)
    at clojure.core$load.invokeStatic(core.clj:5882)
    at clojure.core$load_one.invokeStatic(core.clj:5683)
    at clojure.core$load_one.invoke(core.clj)
    at clojure.core$load_lib$fn__5610.invoke(core.clj:5728)
    at clojure.core$load_lib.invokeStatic(core.clj:5727)
    at clojure.core$load_lib.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:647)
    at clojure.core$load_libs.invokeStatic(core.clj:5765)
    at clojure.core$load_libs.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:649)
    at clojure.core$use.invokeStatic(core.clj:5851)
    at clojure.core$use.doInvoke(core.clj)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at midje.emission.levels$eval196$loading__5553__auto____197.invoke(levels.clj:1)
    at midje.emission.levels$eval196.invokeStatic(levels.clj:1)
    at midje.emission.levels$eval196.invoke(levels.clj)
    at clojure.lang.Compiler.eval(Compiler.java:6934)
    at clojure.lang.Compiler.eval(Compiler.java:6923)
    at clojure.lang.Compiler.load(Compiler.java:7381)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.loadResourceScript(RT.java:363)
    at clojure.lang.RT.load(RT.java:453)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5661.invoke(core.clj:5883)
    at clojure.core$load.invokeStatic(core.clj:5882)
    at clojure.core$load_one.invokeStatic(core.clj:5683)
    at clojure.core$load_one.invoke(core.clj)
    at clojure.core$load_lib$fn__5610.invoke(core.clj:5728)
    at clojure.core$load_lib.invokeStatic(core.clj:5727)
    at clojure.core$load_lib.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:647)
    at clojure.core$load_libs.invokeStatic(core.clj:5765)
    at clojure.core$load_libs.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:647)
    at clojure.core$require.invokeStatic(core.clj:5787)
    at clojure.core$require.doInvoke(core.clj)
    at clojure.lang.RestFn.invoke(RestFn.java:512)
    at midje.config$eval111$loading__5553__auto____112.invoke(config.clj:1)
    at midje.config$eval111.invokeStatic(config.clj:1)
    at midje.config$eval111.invoke(config.clj)
    at clojure.lang.Compiler.eval(Compiler.java:6934)
    at clojure.lang.Compiler.eval(Compiler.java:6923)
    at clojure.lang.Compiler.load(Compiler.java:7381)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.loadResourceScript(RT.java:363)
    at clojure.lang.RT.load(RT.java:453)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5661.invoke(core.clj:5883)
    at clojure.core$load.invokeStatic(core.clj:5882)
    at clojure.core$load_one.invokeStatic(core.clj:5683)
    at clojure.core$load_one.invoke(core.clj)
    at clojure.core$load_lib$fn__5610.invoke(core.clj:5728)
    at clojure.core$load_lib.invokeStatic(core.clj:5727)
    at clojure.core$load_lib.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:647)
    at clojure.core$load_libs.invokeStatic(core.clj:5765)
    at clojure.core$load_libs.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:647)
    at clojure.core$require.invokeStatic(core.clj:5787)
    at clojure.core$require.doInvoke(core.clj)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at user$eval105.invokeStatic(form-init2782805926405860350.clj:1)
    at user$eval105.invoke(form-init2782805926405860350.clj)
    at clojure.lang.Compiler.eval(Compiler.java:6934)
    at clojure.lang.Compiler.eval(Compiler.java:6923)
    at clojure.lang.Compiler.eval(Compiler.java:6923)
    at clojure.lang.Compiler.load(Compiler.java:7381)
    at clojure.lang.Compiler.loadFile(Compiler.java:7319)
    at clojure.main$load_script.invokeStatic(main.clj:275)
    at clojure.main$init_opt.invokeStatic(main.clj:277)
    at clojure.main$init_opt.invoke(main.clj)
    at clojure.main$initialize.invokeStatic(main.clj:308)
    at clojure.main$null_opt.invokeStatic(main.clj:342)
    at clojure.main$null_opt.invoke(main.clj)
    at clojure.main$main.invokeStatic(main.clj:421)
    at clojure.main$main.doInvoke(main.clj)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No matching method: sha1Hex
    at clojure.lang.Compiler$StaticMethodExpr.<init>(Compiler.java:1641)
    at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:1010)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
```

**Comment by belucid** [comment]
@bago2k4 in addition to access token, we want the JWT to contain:

id
name
real_name (might be empty)
email
image_192 (as image)
admin
owner
team/org name
org id

**Comment by bago2k4** [comment]
@belucid this is good to go, the problem w/ the tests was this issue: https://github.com/marick/Midje/issues/323 as you discovered some time ago. i moved midje back to 1.7.0 and now they work.
Also i left a log in the console when you get back from auth to the web service so you can check what's inside the token, check "Preserve logs" to see it before you start the login process.
Let me know if any issue

**Comment by bago2k4** [comment]
@belucid latest commits look good, going to fix the web ui for login now

**Pull request merged**
