### PR TITLE
Slack unfurl support.

### PR DESCRIPTION
**Pull request by thepug**
In order to support the slack unfurl feature we need to search for a user's slack token.  This change to the auth service gives the slack-router the ability to query for this needed data using a "super user" token.

To test you will need to follow the instructions in the slack router service.
https://github.com/open-company/open-company-slack-router#slack-proxy-ngrok
Also use this PR https://github.com/open-company/open-company-slack-router/pull/2

Once you have the slack router receiving slack messages you can test the unfurl.

- Paste a localhost url for a post to a slack channel
- [x] Did it unfurl the content?
 
- Paste a shared public post url to slack.
- [x] Did it unfurl the post information?

- Paste `http://localhost:3559/<org>`
- [x] Did it unfurl the organization info?

- Paste `http://localhost:3559/<org>/<section>`
- [x] Did it unfurl the section information?

### CODE REVIEW

**Comment by thepug** [comment]
[Unfurl post in Slack](https://trello.com/c/cT8YoCfX/1250-unfurl-post-in-slack)

**Comment by belucid** [comment]
@thepug the unfurl is working for a full page post URL. What other URLs should I be testing?

**Comment by belucid** [comment]
@thepug it works but I get this exception w/ each unfurl:

```
18-05-16 22:12:44 Seans-Mac-Pro.local INFO [oc.lib.slack:22] - Making slack request: :chat.unfurl
Wed May 16 18:12:44 EDT 2018 [client-worker-13] ERROR - GET http://localhost:3001/orgs/carrot/boards/general/entries/dc45-425c-b28d's callback
java.lang.Exception: http-kit client deadlock-guard: refusing to deref a request callback from inside a callback. This feature can be disabled with the request's `:deadlock-guard?` option.
	at org.httpkit.client$deadlock_guard$e__34821.invoke(client.clj:143)
	at org.httpkit.client$deadlock_guard$reify__34823.deref(client.clj:148)
	at clojure.core$deref.invokeStatic(core.clj:2312)
	at clojure.core$deref.invoke(core.clj:2298)
	at oc.lib.slack$slack_api.invokeStatic(slack.clj:23)
	at oc.lib.slack$slack_api.invoke(slack.clj:21)
	at oc.lib.slack$unfurl_post_url.invokeStatic(slack.clj:70)
	at oc.lib.slack$unfurl_post_url.invoke(slack.clj:67)
	at oc.slack_router.slack_unfurl$update_slack_url$fn__35157.invoke(slack_unfurl.clj:186)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2312)
	at clojure.core$deref.invoke(core.clj:2298)
	at taoensso.timbre$_log_BANG_.invokeStatic(timbre.clj:358)
	at taoensso.timbre$_log_BANG_.invoke(timbre.clj:345)
	at oc.slack_router.slack_unfurl$update_slack_url.invokeStatic(slack_unfurl.clj:185)
	at oc.slack_router.slack_unfurl$update_slack_url.invoke(slack_unfurl.clj:164)
	at oc.slack_router.slack_unfurl$unfurl$fn__35168.invoke(slack_unfurl.clj:274)
	at oc.slack_router.slack_unfurl$get_data$fn__35144.invoke(slack_unfurl.clj:71)
	at org.httpkit.client$request$deliver_resp__34834$fn__34835.invoke(client.clj:217)
	at org.httpkit.client$request$deliver_resp__34834.invoke(client.clj:215)
	at org.httpkit.client$request$reify__34839.onSuccess(client.clj:244)
	at org.httpkit.client.Handler.run(RespListener.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Thoughts?

**Comment by belucid** [comment]
NB: @thepug the above exception only seems to happen with `http-kit "2.3.0", not `http-kit "2.3.0-beta2", which is presumably why you haven't seen it before.

So fine to leave it on beta-2 for now, but definitely something we want to understand.

**Comment by thepug** [comment]
@belucid So it looks like because I use http kit to retrieve info from the auth service 
https://github.com/open-company/open-company-slack-router/blob/mainline/src/oc/slack_router/slack_unfurl.clj#L66

That sets the single variable `in-callback` https://github.com/http-kit/http-kit/blob/master/src/org/httpkit/client.clj#L148

When I make the slack unfurl request in that callback we get the deadlock message.  The slack request doesn't use a callback so it really shouldn't send that message. I think its a bug in http-kit

**Comment by thepug** [comment]
@belucid added some more test steps

**Pull request merged**
