### PR TITLE
UX desktop: update user avatar

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/V8or3gsm

To test:
- clean local DB
- signup with email using your Slack email
- remove opencompany.com as email domain
- insert only the first name, not the last name
- once you are in add a Slack team with the user that has the same email
- [x] did it pull your avatar? Good
- [x] did it leave your first name only, no last name added? Good
- now logout
- onboard with one of our Slack test orgs
- [x] did it pull in your first/last name, avatar, team name and logo? Good

### CODE REVIEW

**Comment by bago2k4** [comment]
[UX desktop: update user avatar](https://trello.com/c/V8or3gsm/1881-ux-desktop-update-user-avatar)

**Comment by belucid** [comment]
kibit issue on this one @bago2k4

**Comment by bago2k4** [comment]
@belucid fixed

**Comment by belucid** [comment]
@bago2k4 we should do the same thing for the org, pull the logo from Slack if the org doesn't have one at the time they add Slack. More involved though. I'll card it up separately.

**Pull request merged**
