### PR TITLE
Sort enumerated users.

### PR DESCRIPTION
**Pull request by belucid**
https://trello.com/c/vH9WyAmm

1 liner change.

### CODE REVIEW

**Comment by bago2k4** [comment]
reviewing

**Review by bago2k4 — COMMENTED** [review]
https://www.evernote.com/shard/s29/sh/250c2107-71be-4d35-866c-d8aa1e00578a/071a94a433720e168857d033cf391125
I don't think this sorting would help the user.. we should sort for name/surname but sometimes we don't have them, ie: i just invited my whole team. So we can sort for the first part of the email? or we consider this a special case?

**Comment by belucid** [comment]
The email, especially company email, is usually a decent enough surrogate for the user's name. Seems important that the sort be consistent, and not move from name to email when name isn't there.

**Comment by bago2k4** [comment]
ok, merging

**Pull request merged**
