### PR TITLE
rename auth-url to basic-scopes-url

### PR DESCRIPTION
**Pull request by martinklepsch**
Web PR: https://github.com/open-company/open-company-web/pull/160 — merge after #6

`auth-url` isn't used in the app until this card is addressed: https://trello.com/c/yMchqZEe/447-non-bot-user-auth-access (PR coming).

I thought auth-url isn't particularly helpful when trying to understand the difference to `extended-scopes-url` so now seems a good time to rename.

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by martinklepsch** [comment]
@belucid I updated this to fix the issue you mentioned in the Web PR.

Unfortunately Slack returns different responses when OAuthing with different scopes so the team name is missing for instance. Eventually we should address this by fetching team info separately if it is missing but lets put that in another card. The essential bit (org-id) is there.

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@martinklepsch 

I still get an error auth'ing w/ Clojurians using the link:

```
Mon Jul 18 08:19:30 EDT 2016 [worker-2] ERROR - GET /slack-oauth
clojure.lang.ExceptionInfo: Error response from Slack API while retrieving user data {:response {:ok false, :error "missing_scope", :needed "users:read", :provided "identity.basic"}, :user-id "U076Q2MHA"}
    at clojure.core$ex_info.invokeStatic(core.clj:4724)
    at clojure.core$ex_info.invoke(core.clj:4724)
    at open_company_auth.slack$get_user_info.invokeStatic(slack.clj:49)
    at open_company_auth.slack$get_user_info.invoke(slack.clj:34)
    at open_company_auth.slack$swap_code_for_token.invokeStatic(slack.clj:81)
    at open_company_auth.slack$swap_code_for_token.invoke(slack.clj:63)
    at open_company_auth.slack$oauth_callback.invokeStatic(slack.clj:99)
    at open_company_auth.slack$oauth_callback.invoke(slack.clj:91)
    at open_company_auth.app$oauth_callback.invokeStatic(app.clj:50)
    at open_company_auth.app$oauth_callback.invoke(app.clj:47)
    at open_company_auth.app$fn__11936.invokeStatic(app.clj:65)
    at open_company_auth.app$fn__11936.invoke(app.clj:65)
    at compojure.core$make_route$fn__5127.invoke(core.clj:135)
    at compojure.core$wrap_route_middleware$fn__5120.invoke(core.clj:122)
    at compojure.core$wrap_route_info$fn__5124.invoke(core.clj:126)
    at compojure.core$if_route$fn__5072.invoke(core.clj:45)
    at compojure.core$if_method$fn__5062.invoke(core.clj:27)
    at compojure.core$routing$fn__5134.invoke(core.clj:151)
    at clojure.core$some.invokeStatic(core.clj:2673)
    at clojure.core$some.invoke(core.clj:2664)
    at compojure.core$routing.invokeStatic(core.clj:151)
    at compojure.core$routing.doInvoke(core.clj:148)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invokeStatic(core.clj:659)
    at clojure.core$apply.invoke(core.clj:652)
    at compojure.core$routes$fn__5138.invoke(core.clj:156)
    at clojure.lang.Var.invoke(Var.java:379)
    at ring.middleware.reload$wrap_reload$fn__5844.invoke(reload.clj:39)
    at ring.middleware.params$wrap_params$fn__5300.invoke(params.clj:67)
    at ring.middleware.cors$allow_origins.invokeStatic(cors.clj:48)
    at ring.middleware.cors$allow_origins.doInvoke(cors.clj:41)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:661)
    at clojure.core$apply.invoke(core.clj:652)
    at ring.middleware.cors$wrap_cors$fn__5885.invoke(cors.clj:59)
    at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by martinklepsch** [comment]
@belucid ready again

This adds a dependency on [truss](https://github.com/ptaoussanis/truss) which is a minimal assertion library, we could've used Schema but I like truss' minimalism for now.

**Pull request merged**
