### PR TITLE
Always ask for the permission to write comment as user. 

### PR DESCRIPTION
**Pull request by thepug**
Bot permission is asked for only if bot is not part of the team.

To test:
First see the SLACK_TESTING document in infrastructure to get slack account info.

- Login as owner of slack workspace and authorize the carrot bot.
- Login to slack as a non owner
- Invite the non owner to carrot as an admin.
- [x] Does the carrot app notify you that you have an invite?

- Signup with the invited user.
- Create a section that posts to slack .
- Create a post in that section
- [ ] Does it show the post from the carrot app in the slack channel?
- Comment on the post
- [ ] Does it show the comment as the correct slack user?

### CODE REVIEW

**Comment by thepug** [comment]
I'm going to put this in review, but not sure what other slack actions we take besides commenting that requires the write as user permission.

**Comment by thepug** [comment]
[Need a 3rd type of Slack auth, when team has bot already](https://trello.com/c/cgLWZESD/1169-need-a-3rd-type-of-slack-auth-when-team-has-bot-already)

**Comment by belucid** [comment]
@thepug sharing to Slack and inviting via Slack should both take advantage of the write permission when we have it as well.

I believe only the former does right now, there is a card in the current sprint for the latter to do so.

**Comment by bago2k4** [comment]
@thepug i think this is a hard stop! non owner users can't install the bot...
screen shot 2018-04-17 at 8 29 11 pm

I signed up with test-org-2, first admin was the first user in, invited the second user that was Jane (first non owner of the org).
Jane got the notification and when i tried to signup with her i got the screenshot above on the second round of permissions

**Comment by thepug** [comment]
RE: https://github.com/open-company/open-company-auth/pull/32#issuecomment-382095884

so I am able to recreate this screen.  The strange thing is that I am not asking to install a bot and I have verified that none of the scope requests are for the bot.  Also this used to work ☹️   With the slack oauth requests you are suppose to be able to ask for new permissions/scope at anytime. So this really shouldn't be a thing.

**Comment by thepug** [comment]
Also non-owner users always get this,https://github.com/open-company/open-company-auth/pull/32#issuecomment-382095884, message if the bot hasn't been installed.

**Pull request closed without merging**
